name: Test app
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: START
        run: echo "STARTING......"
      - name: GET CODE
        uses: actions/checkout@v3
      - name: INSTALL NODEJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: INSTALL DEPENDENCIES
        run: npm ci
      - name: RUN TESTS
        run: npm test
